site_name: OSMOND
repo_name: prajeeshag/osmond
repo_url: https://github.com/prajeeshag/osmond
theme:
  name: material
  palette:
    primary: "indigo"
    accent: "pink"
  font:
    text: "Roboto"
    code: "Fira Code"

markdown_extensions:
  - attr_list

plugins:
  - termynal
  - mkdocstrings:
      handlers:
        python:
          options:
            annotations_path: brief

nav:
  - Home: index.md
  - API reference: api_reference.md
