[build-system]
requires = ["setuptools >= 61.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "medslik_ondemand"
dynamic = ["version"]
description = ""
authors = [{ name = "Prajeesh Ag", email = "prajeeshag@gmail.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "xarray",
    "netCDF4",
    "typer",
    "dask",
    "cartopy",
    "geopandas",
    "pydantic>=2.9.2",
]

[project.scripts]
medslik_ondemand = "medslik_ondemand:app"

[project.urls]
homepage = "https://prajeeshag.github.io/medslik_ondemand"
repository = "https://github.com/prajeeshag/medslik_ondemand"
documentation = "https://prajeeshag.github.io/medslik_ondemand"

[tool.setuptools.packages.find]
exclude = ["tests", "docs"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "node-and-timestamp"

[tool.setuptools.package-data]
"medslik_ondemand" = ["static/*"]

[tool.commitizen]
name = "cz_gitmoji"

[tool.uv]
dev-dependencies = [
    "commitizen>=3.30.0",
    "cz-conventional-gitmoji>=0.6.1",
    "ruff>=0.7.1",
]
